package com.mtgdb.mtgdatabase.cards.attributes;

public enum SubType {
    //CREATURE subtypes
    ANGEL, ARCHER, ASSASSIN, AVATAR, BARBARIAN, BASILISK, BEAR, BEAST, BIRD, CAT, CLERIC, COCKATRICE, DEMON,
    DINOSAUR, DJINN, DRAGON, DRUID, DRYAD, DWARF, ELEMENTAL, ELEPHANT, ELF, FAERIE, FUNGUS, GARGOYLE, GIANT,
    GOBLIN, GOLEM, HORSE, HUMAN, HYDRA, ILLUSION, IMP, INCARNATION, JUGGERNAUT, KNIGHT, MERFOLK, MINOTAUR,
    NIGHTMARE, NYMPH, OGRE, ORC, PEGASUS, PIRATE, PLANT, RAT, SERPENT, SHADE, SHAPESHIFTER, SKELETON, SOLDIER,
    SPECTER, SPIDER, TREEFOLK, TROLL, UNICORN, VAMPIRE, WALL, WARRIOR, WIZARD, WOLF, WRAITH, WURM, ZOMBIE,

    //ENCHANTMENT subtypes
    AURA, CARTOUCHE,

    //ARTIFACT subtypes
    EQUIPMENT,

    //BASIC LAND subtypes
    PLAINS, ISLAND, SWAMP, MOUNTAIN, FOREST,

    //INSTANT AND SORCERY subtypes
    ARCANE, ADVENTURE,

    //if the card has no subtypes
    NONE
}
